#!/usr/bin/env bash
# agent/score.sh [<matrix-out-dir>…] — merge auto.tsv (the script's rows) and
# score.tsv (the reader's rows) of every session under the given matrix
# directories (default: the newest under out/agent/) into REPORT-agent.md:
# one table per task, rows = artifact·row, one column per model, cells
# P (pass) · p (partial) · F (fail) · – (n/a); then cost, turns, duration,
# hook counters per task and model; then a diff list of every split.
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
DIRS=("$@")
[ ${#DIRS[@]} -gt 0 ] || DIRS=("$(ls -d "$OUT_DIR"/agent/*/ 2>/dev/null | sort | tail -1)")
[ -n "${DIRS[0]:-}" ] && [ -d "${DIRS[0]}" ] || fail "no matrix under $OUT_DIR/agent"
REPORT="${LAB_REPORT:-$LAB_DIR/REPORT-agent.md}"   # the real leg writes under out/, never the committed report
TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
# rows: dir model task artifact row score
for d in "${DIRS[@]}"; do
  for meta in "$d"/*/*/meta.tsv; do
    [ -f "$meta" ] || continue
    sdir=$(dirname "$meta"); model=$(basename "$(dirname "$sdir")"); task=$(basename "$sdir")
    for f in "$sdir/auto.tsv" "$sdir/score.tsv"; do
      [ -f "$f" ] || continue
      awk -F'\t' -v m="$model" -v t="$task" '$3 != "" { printf("%s\t%s\t%s\t%s\t%s\n", t, m, $1, $2, $3) }' "$f"
    done
  done
done > "$TMP/rows.tsv"
for d in "${DIRS[@]}"; do
  for meta in "$d"/*/*/meta.tsv; do
    [ -f "$meta" ] || continue
    sdir=$(dirname "$meta"); model=$(basename "$(dirname "$sdir")"); task=$(basename "$sdir")
    g() { awk -F'\t' -v k="$1" '$1 == k { print $2 }' "$meta"; }
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$task" "$model" "$(g model_id)" "$(g cost_usd)" "$(g turns)" "$(g duration_ms)" "$(g exit)" "$(g hook_r023)" "$(g commits)"
  done
done > "$TMP/meta.tsv"
mapfile -t models < <(cut -f2 "$TMP/rows.tsv" | sort -u)
mapfile -t tasks < <(cut -f1 "$TMP/rows.tsv" | sort -u)
cell() { case "$1" in pass) printf P ;; partial) printf p ;; fail) printf F ;; n/a) printf – ;; *) printf '?' ;; esac; }
{
  printf '# Agent report\n\n'
  printf 'Generated by `ci/agent-lab/agent/score.sh` on %s from %s. Rows marked in `rubric.md` as\n' "$(date +%F)" "${DIRS[*]##*/out/}"
  printf 'auto come from `agent/checks.sh`; the rest from the reader'"'"'s `score.tsv`. Cells: P pass · p partial · F fail · – n/a.\n\n'
  printf '## Sessions\n\n| task | model | resolved model | cost USD | turns | duration ms | exit | R-023 blocks | commits |\n|---|---|---|---|---|---|---|---|---|\n'
  sort "$TMP/meta.tsv" | awk -F'\t' '{ printf("| %s | %s | %s | %s | %s | %s | %s | %s | %s |\n", $1, $2, $3, $4, $5, $6, $7, $8, $9) }'
  printf '\n'
  for t in "${tasks[@]}"; do
    printf '## %s\n\n| artifact · row |' "$t"
    for m in "${models[@]}"; do printf ' %s |' "$m"; done
    printf '\n|---|'; for _ in "${models[@]}"; do printf -- '---|'; done; printf '\n'
    awk -F'\t' -v t="$t" '$1 == t { print $3 "\t" $4 }' "$TMP/rows.tsv" | sort -u | while IFS=$'\t' read -r a r; do
      printf '| %s · %s |' "$a" "$r"
      for m in "${models[@]}"; do
        s=$(awk -F'\t' -v t="$t" -v m="$m" -v a="$a" -v r="$r" '$1 == t && $2 == m && $3 == a && $4 == r { print $5; exit }' "$TMP/rows.tsv")
        printf ' %s |' "$(cell "${s:-}")"
      done
      printf '\n'
    done
    printf '\n'
  done
  if [ ${#models[@]} -ge 2 ]; then
    printf '## Splits (pass for one model, fail for the other)\n\n'
    awk -F'\t' '{ k = $1 "\t" $3 "\t" $4; if (!((k, $2) in seen)) { seen[k, $2] = 1; v[k] = v[k] " " $2 "=" $5 } } END { for (k in v) if (v[k] ~ /=pass/ && v[k] ~ /=fail/) print k "\t" v[k] }' "$TMP/rows.tsv" | sort | awk -F'\t' '{ printf("- %s · %s · %s —%s\n", $1, $2, $3, $4) }'
    printf '\n'
  fi
} > "$REPORT"
printf 'report: %s (%s rows, %s sessions)\n' "$REPORT" "$(wc -l < "$TMP/rows.tsv" | tr -d ' ')" "$(wc -l < "$TMP/meta.tsv" | tr -d ' ')"
