#!/usr/bin/env bash
# mech/run.sh [--out <dir>] [flow…] — the mechanical harness: every flow's
# exact expectations, no agent, no network, under three minutes. Writes
# <out>/results.tsv (flow, check, PASS|FAIL, evidence) and the committed
# REPORT-mechanical.md beside this directory. Exit 1 when any check fails.
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"
lab_binary
OUT="$OUT_DIR/mech/$(date +%Y%m%d-%H%M%S)"
FLOWS=()
while [ $# -gt 0 ]; do
  case "$1" in
    --out) OUT=$2; shift 2 ;;
    *) FLOWS+=("$1"); shift ;;
  esac
done
[ ${#FLOWS[@]} -gt 0 ] || FLOWS=(kb-ingest graduate learn brownfield)
mkdir -p "$OUT"
WORK=$(lab_workdir mech)
trap 'rm -rf "$WORK"' EXIT
export RESULTS="$OUT/results.tsv"
: > "$RESULTS"
export TMPDIR="$WORK/tmp"; mkdir -p "$TMPDIR"
{ printf 'docsys at %s\n' "$(command -v docsys)"; sha256_of "$(command -v docsys)"; } > "$OUT/binary.txt"
status=0
for f in "${FLOWS[@]}"; do
  say "flow: $f"
  if "$LAB_DIR/mech/$f.sh" "$WORK/$f" > "$OUT/$f.log" 2>&1; then
    tail -1 "$OUT/$f.log"
  else
    status=1
    (grep -E '^FAIL|LAB FAIL|passed' "$OUT/$f.log" || true) | tail -20
    printf 'flow %s ended without a summary — its log: %s\n' "$f" "$OUT/$f.log"
    mkdir -p "$OUT/$f-failed" && cp -R "$WORK/$f/out" "$OUT/$f-failed/" 2>/dev/null || true
  fi
done

# the report: one table per flow, synthetic rows only
{
  printf '# Mechanical report\n\n'
  printf 'Generated by `ci/agent-lab/mech/run.sh` on %s. Every row is a synthetic fixture and an exact\n' "$(date +%F)"
  printf 'expectation; a FAIL names the string that was missing. Binary: `%s`.\n\n' "$(tail -1 "$OUT/binary.txt" | cut -c1-16)"
  total=$(wc -l < "$RESULTS" | tr -d ' ')
  pass=$(grep -c "$(printf '\tPASS\t')" "$RESULTS" || true)
  failc=$(grep -c "$(printf '\tFAIL\t')" "$RESULTS" || true)
  printf '**%s checks · %s passed · %s failed**\n\n' "$total" "$pass" "$failc"
  for f in "${FLOWS[@]}"; do
    printf '## %s\n\n| check | result | evidence |\n|---|---|---|\n' "$f"
    awk -F'\t' -v f="$f" '$1 == f { e = $4; gsub(/\|/, "\\|", e); gsub(/`/, "\\`", e); printf("| %s | %s | %s |\n", $2, $3, e) }' "$RESULTS"
    printf '\n'
  done
} > "$LAB_DIR/REPORT-mechanical.md"
printf '\nresults: %s\nreport:  %s\n' "$RESULTS" "$LAB_DIR/REPORT-mechanical.md"
exit $status
