//! `docsys rules` — agent-facing rule text, generated from the specification
//! (R-155). The spec is embedded at build time; nothing here is a hand-written
//! copy, so the text cannot drift from the rules the way §18's prose history
//! once did. Two layers, matching progressive disclosure:
//!   --agents-md    the always-loaded block (budget-checked, R-165)
//!   --procedures   the fifteen decision procedures of §14.3, verbatim

/// The specification this binary implements, embedded verbatim.
pub const SPEC: &str = include_str!("../SPEC.md");

/// Extract the body of a section by its exact heading line, up to the next
/// heading of equal-or-higher level.
fn section(heading: &str) -> Option<String> {
    let mut out = String::new();
    let mut inside = false;
    let level = heading.chars().take_while(|c| *c == '#').count();
    for line in SPEC.lines() {
        if inside {
            let l = line.chars().take_while(|c| *c == '#').count();
            if l > 0 && l <= level && line.starts_with('#') {
                break;
            }
            out.push_str(line);
            out.push('\n');
        } else if line.trim_end() == heading {
            inside = true;
        }
    }
    if inside {
        Some(out)
    } else {
        None
    }
}

/// The fifteen authored decision procedures (§14.3), rendered verbatim —
/// transformation, not authorship (R-005/R-155). R-163 forbids inventing
/// anything absent from this text.
pub fn procedures() -> Option<String> {
    let body = section("### 14.3 The authored procedures")?;
    let mut out = String::from(
        "# Decision procedures (generated from SPEC.md — do not edit)\n\
         #\n\
         # Format per §14.2: EVIDENCE · QUESTION · OPTIONS (closed, first match\n\
         # wins) · DEFAULT · ESCAPE (always legitimate) · VERIFY · NEVER.\n",
    );
    out.push_str(&body);
    Some(out)
}

/// First sentence of a rule's text, for the always-loaded summary. Mechanical
/// extraction (the R-057 pattern): everything up to the first `. ` boundary.
fn first_sentence(text: &str) -> String {
    let joined = text.split_whitespace().collect::<Vec<_>>().join(" ");
    match joined.split_once(". ") {
        Some((s, _)) => format!("{s}."),
        None => joined,
    }
}

/// The always-loaded block for AGENTS.md. Contents are derived: every
/// `agent`-tagged rule's number and first sentence, extracted from the
/// embedded spec — plus the fixed tool-gate lines (UI text, not rule prose).
pub fn agents_md() -> String {
    let mut rules: Vec<(String, String)> = Vec::new();
    let mut current: Option<(String, String)> = None;
    for line in SPEC.lines() {
        if let Some(rest) = line.strip_prefix("**R-") {
            if let Some((num, tail)) = rest.split_once("** ") {
                // close the previous rule
                if let Some((id, text)) = current.take() {
                    rules.push((id, first_sentence(&text)));
                }
                if tail.starts_with("`agent`") {
                    let text = tail.split_once("— ").map(|(_, t)| t).unwrap_or("");
                    current = Some((format!("R-{num}"), text.to_string()));
                }
                continue;
            }
        }
        if let Some((_, ref mut text)) = current {
            if line.trim().is_empty() || line.starts_with('#') || line.starts_with('>') {
                if let Some((id, text)) = current.take() {
                    rules.push((id, first_sentence(&text)));
                }
            } else {
                text.push(' ');
                text.push_str(line.trim());
            }
        }
    }
    if let Some((id, text)) = current.take() {
        rules.push((id, first_sentence(&text)));
    }

    let spec_version = SPEC
        .lines()
        .find_map(|l| l.strip_prefix("**Version:** "))
        .unwrap_or("?")
        .trim();

    let mut out = format!(
        "## Documentation (generated by `docsys rules --agents-md`, spec {spec_version} — do not edit)\n\n\
         Layout: `reference/` (facts the code cannot state) · `howto/` (procedures) ·\n\
         `explanation/` (why; ADRs) · `work/` (flowing: journal, features, postmortems,\n\
         research, debt, questions). `index.md` routes every permanent page.\n\n\
         Mechanics are the tool's job — run them, never re-derive them:\n\
         - `docsys lint` before every commit; errors block, warnings accumulate\n\
         - `docsys refs --repo .` when code references documentation\n\
         - code cites documentation as `doc: <id>` — never a path; the id is the\n\
           contract, the filename is cosmetic\n\
         - a blocked Bash call is blocked whole: `git add … && git commit` re-runs\n\
           from the `add`; what landed is `git show HEAD:<file>`, not the tree\n\n\
         Judgment stays with you, but inside these rules:\n"
    );
    for (id, sentence) in &rules {
        out.push_str(&format!("- {id}: {sentence}\n"));
    }
    out.push_str(
        "\nWhen a decision procedure exists, follow it: `docsys rules --procedures`.\n\
         When no option fits, the escape is always legitimate — an honest \"I don't\n\
         know\" (an `_unsorted/` file, a `questions.md` item) is cheaper than a\n\
         confident guess.\n",
    );
    out
}

/// R-165: the always-loaded text must fit the budget; the floor is the
/// rendered mandatory set. Returns Err with an explanation when violated.
pub fn check_budget(max_lines: usize) -> Result<(usize, usize), String> {
    let summary_lines = agents_md().lines().count();
    let floor = summary_lines;
    if max_lines < floor {
        return Err(format!(
            "agent_rules_max_lines {max_lines} is below the floor {floor} — a budget \
             that silently drops mandatory text is R-151's \"silently wrong\""
        ));
    }
    if summary_lines > max_lines {
        return Err(format!(
            "generated summary is {summary_lines} lines, over the {max_lines} budget"
        ));
    }
    Ok((summary_lines, max_lines))
}

const BLOCK_BEGIN: &str = "<!-- docsys:rules:begin — generated, do not edit inside -->";
const BLOCK_END: &str = "<!-- docsys:rules:end -->";

/// Write/update the generated block inside a managed marker region of `path`.
/// Owner prose outside the markers is never touched; re-runs are idempotent.
pub fn write_agents_block(path: &std::path::Path) -> Result<&'static str, String> {
    let block = format!("{BLOCK_BEGIN}\n{}{BLOCK_END}\n", agents_md());
    let existing = std::fs::read_to_string(path).ok();
    let new_text = match existing {
        None => block.clone(),
        Some(text) => match (text.find(BLOCK_BEGIN), text.find(BLOCK_END)) {
            (Some(a), Some(b)) if b > a => {
                let after = text.get(b + BLOCK_END.len()..).unwrap_or("");
                format!(
                    "{}{block}{}",
                    text.get(..a).unwrap_or(""),
                    after.trim_start_matches('\n')
                )
            }
            _ => {
                let sep = if text.ends_with('\n') { "\n" } else { "\n\n" };
                format!("{text}{sep}{block}")
            }
        },
    };
    std::fs::write(path, new_text).map_err(|e| e.to_string())?;
    Ok("written")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn procedures_render_verbatim_from_spec() {
        let p = procedures().unwrap_or_default();
        assert!(p.contains("P/R-031"), "type-selection procedure present");
        assert!(p.contains("P/R-123"), "translation procedure present");
        assert!(p.contains("NEVER"), "format fields present");
    }

    #[test]
    fn agents_md_lists_agent_rules_and_fits_default_budget() {
        let s = agents_md();
        assert!(s.contains("R-031:"), "{s}");
        assert!(s.contains("R-081:"), "{s}");
        assert!(s.contains("doc: <id>"));
        let lines = s.lines().count();
        assert!(
            lines <= 200,
            "summary is {lines} lines — over the default budget"
        );
    }
}
#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]
mod tests_more {
    use super::*;

    #[test]
    fn a_spec_section_is_cut_at_the_next_heading_of_its_level() {
        let s = section("## 19. Open questions").expect("section exists in SPEC");
        assert!(s.contains("Identifier-based document links"), "{s}");
        assert!(section("## no such heading").is_none());
        let sub = section("### 14.3 The authored procedures").unwrap();
        assert!(!sub.contains("\n## "), "stops before the next H2");
    }

    #[test]
    fn first_sentence_is_cut_at_the_first_boundary() {
        assert_eq!(first_sentence("One two.  Three\nfour."), "One two.");
        assert_eq!(first_sentence("No boundary here"), "No boundary here");
        assert_eq!(first_sentence("v1.2 is fine. Next"), "v1.2 is fine.");
        assert_eq!(first_sentence("  spaced\n  out  "), "spaced out");
    }

    #[test]
    fn the_budget_has_a_floor_and_a_ceiling() {
        let (lines, max) = check_budget(200).unwrap();
        assert!(lines <= max);
        let err = check_budget(1).unwrap_err();
        assert!(err.contains("below the floor"), "{err}");
        assert!(procedures().unwrap().starts_with("# Decision procedures"));
    }
}
